[package]
name = "pufb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="3.0.0-beta.4"
regex = "1.6.0"
encoding_rs_io = "0.1.7"
encoding_rs = "0.8.28"
string-builder = "0.2.0"